# appveyor.yml

clone_folder: c:\gopath\src\github.com\jumpjet-co\jumpjet-cli

environment:
  GOPATH: c:\gopath

stack: go 1.12.3

build_script:
  - go get ./...
  - go build -o jumpjet.exe

artifacts:
  - path: jumpjet.exe
    name: jumpjet.exe

deploy:
  - release: $(appveyor_repo_tag_name)
    description: Windows binary
    provider: GitHub
    auth_token:
      secure: UoNS/cfkAKZVzPlsFHZE8SDrnaEAV85ZV1aHT7PrVrjE6qZun+Tgj1HjJqnrE1nz
    artifact: jumpjet.exe
    draft: true
    prerelease: false
    on:
      APPVEYOR_REPO_TAG: true